---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-aloys-aloys-io-v1-nodemodifyresources
    failurePolicy: Fail
    name: mnodemodifyresources.kb.io
    rules:
      - apiGroups:
          - aloys.aloys.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - nodemodifyresources
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-aloys-aloys-io-v1-nodemodifyresources
    failurePolicy: Fail
    name: vnodemodifyresources.kb.io
    rules:
      - apiGroups:
          - aloys.aloys.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - nodemodifyresources
    sideEffects: None
