# permissions for end users to view nodemodifyresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nodemodifyresources-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: node-samples
    app.kubernetes.io/part-of: node-samples
    app.kubernetes.io/managed-by: kustomize
  name: nodemodifyresources-viewer-role
rules:
  - apiGroups:
      - aloys.aloys.io
    resources:
      - nodemodifyresources
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - aloys.aloys.io
    resources:
      - nodemodifyresources/status
    verbs:
      - get
