---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  - apiGroups:
      - aloys.aloys.io
    resources:
      - nodemodifyresources
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aloys.aloys.io
    resources:
      - nodemodifyresources/finalizers
    verbs:
      - update
  - apiGroups:
      - aloys.aloys.io
    resources:
      - nodemodifyresources/status
    verbs:
      - get
      - patch
      - update
